version: 2.0
jobs:
  build:
    docker:
      - image: selenium/standalone-chrome:3.1.0
    steps:
      - checkout
      - run:
          name: Code has arrived!
          command: |
            ls -l
            echo 'Does this look familiar?'
            echo 'This is the delivery pipeline'
      - run:
          name: Update
          command: sudo apt-get update
      - run:
          name: Download Hugo
          command: wget https://github.com/spf13/hugo/releases/download/v0.14/hugo_0.14_amd64.deb
      - run:
          name: Install Hugo
          command: sudo dpkg -i hugo*.deb
      - run:
          name: Check Hugo
          command: hugo version
      - run:
          name: Download Hugo
          command: wget https://www.dropbox.com/s/nx12d36ohc9il6k/helium-python-2.0.3-linux.zip?dl=0
