version: 2.0
jobs:
  build:
    docker:
      - image: selenium/standalone-chrome:3.1.0
    steps:
      - checkout
      - run:
          name: Code has arrived!
          command: |
            ls -l
            echo 'Does this look familiar?'
            echo 'This is the delivery pipeline'
